### ISSUE TITLE
京东夺宝岛失效了 https://paipai.jd.com/auction-list/

### ISSUE THREAD

**Issue by zimaoxy** [hoothin/UserScripts#683]
https://paipai.jd.com/auction-list/

之前可以自动翻页, 这几天无法翻页了

**Comment by hoothin** [comment]
更新试试

**Comment by zimaoxy** [comment]
更新后, 可以加载了, 但是加载速度特别慢, 最慢的一页要一分多钟, 怀疑是网站加了读取限制, 打开控制台提示如下:
![image](https://github.com/user-attachments/assets/c967cb06-4011-421a-a0d2-c2151d155220)

Failed to load resource: the server responded with a status of 499 ()
userscript.html?name=Pagetual.user.js&id=5bce79ce-5c0e-4774-b4f9-9f3b04a89e06:1009 【Pagetual v.1.9.37.86】 Next link: <button type=​"button" class=​"btn-next">​…​</button>​
userscript.html?name=Pagetual.user.js&id=5bce79ce-5c0e-4774-b4f9-9f3b04a89e06:1009 【Pagetual v.1.9.37.86】 Page element: body > div.pp-shortcut-wrap+div > div.auction-list > div.list-selector > div.container > div.auction-selector+div > ul.gl-wrap
%7B%22pageNo%22%3A1%2C%22pageSize%22%3A50%2C%22category1%22%3A%22%22%2C%22status%22%3A%22%22%2C%22orderDirection%22%3A1%2C%22orderType%22%3A1%2C%22groupId%22%3A1000002%7D:1  An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.gif:1 
        
        
        Failed to load resource: the server responded with a status of 499 ()
vendor.79ce160786fa2965228f.js:6  Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/auction-list/%7B%22pageNo%22%3A1%2C%22pageSize%22%3A50%2C%22category1%22%3A%22%22%2C%22status%22%3A%22%22%2C%22orderDirection%22%3A1%2C%22orderType%22%3A1%2C%22groupId%22%3A1000002%7D?entryid=".
    at Ot (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:17390)
    at Rt.confirmTransition (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:20273)
    at Rt.transitionTo (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:19654)
    at e.push (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:22622)
    at https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:27356
    at new Promise (<anonymous>)
    at Ht.push (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:6:27320)
    at a.redirect (https://paipai.jd.com/jdbjk-static/js/11.d0baff0823988e5fc86e.js:1:8653)
    at a.handlePageIndexChange (https://paipai.jd.com/jdbjk-static/js/11.d0baff0823988e5fc86e.js:1:8529)
    at Vt (https://paipai.jd.com/jdbjk-static/js/vendor.79ce160786fa2965228f.js:53:11325)

**Comment by hoothin** [comment]
我这没问题，估计是你的 ip 被京东风控了吧
![image](https://github.com/user-attachments/assets/0ac69d9f-af7e-42db-b94d-30290d6f28e4)

**Comment by zimaoxy** [comment]
不应该呀, 我没做什么频繁刷新的脚本之类, 我只是之前修改了下配置, 然后就发现这个问题了, 改回原来设置后, 问题依旧存在, 不知道跟这个有没有关系
![pagetual hoothin com_cn_rule html (1)](https://github.com/user-attachments/assets/d6bc0fdd-1928-49a9-a4a8-6b4cf8b90c91)

**Comment by hoothin** [comment]
那是京东说了算。
我看了一下，你的设置应该没啥问题。

**Comment by zimaoxy** [comment]
好吧, 设置没问题的话, 那应该就是京东抽风了
